### ISSUE TITLE
Create a Simple form to calculate Income Values

### ISSUE THREAD

**Issue by philbick** [philbick/pslip#2]
#### The form should include inputs for 
- First Name
- Last Name
- Annual Salary
- Super Rate
- Payment Start Date

#### The form should generate payslip information with 
- Name (- Will assume First Name + Last Name)
- Pay Period
- Gross Income
- Income Tax
- Net Income
- Super

#### With Calculation being the following
- pay period = per calendar month
- gross income = annual salary / 12 months
- income tax = based on the tax table provide below
- net income = gross income - income tax
- super = gross income x super rate

### Notes 
All calculation results should be rounded to the whole dollar. If >= 50 cents round up to the next dollar increment, otherwise round down.

### Tasks
- [ ] Create visible inputs with placeholders of their expected input
- [ ] Ability for the form to submit results and Validate all input has been given and is in the expected format
- [ ] Display Calculation results on screen
