### ISSUE TITLE
Add ability to Upload Files

### ISSUE THREAD

**Issue by philbick** [philbick/pslip#3]
#### File constraints
- Limit format of File to CSV for simplicity
- Limit File size to 2MB

#### Contents formatting
- File shall not have headers
- File shall have data in the following Order
     - first name
     - last name
     - annual salary
     - super rate
     - payment start date

### Notes
- Initially file Upload will simply deprecate the use of input & trigger calculation and display of results on screen

### Tasks
- [ ] Create Input to select a file to upload
- [ ] Create Validation for the file format / size / contents
- [ ] Pass on values for calculation
